### ISSUE TITLE
How to load  oscar data for specific language on hugging-face 

### ISSUE THREAD

**Issue by IsraelAbebe** [oscar-project/corpus#20]
from datasets import load_dataset

dataset = load_dataset("oscar-corpus/OSCAR-2201", use_auth_token=True)

**Comment by Uinelj** [comment]
Hello!

The syntax is as follows (I'll take the Basque (code=`eus`) as an example):

```
from datasets import load_dataset

dataset = load_dataset("oscar-corpus/OSCAR-2201", "eus", use_auth_token=True)
```

However I checked the Datasets page and this information is not displayed. I'll do this this week.

Thank you for the report and do not hesitate to reopen if you still experience problems using OSCAR!

**Comment by MAHMOUDRR707** [comment]
I am facing the same problem with  3201 @Uinelj

**Comment by Uinelj** [comment]
Hello @MAHMOUDRR707 . We're still working on the HuggingFace import script so right now you can't use `load_dataset` to load OSCAR 23.01. However, you can use git LFS to get the raw data: https://oscar-project.org/faq/#how-can-i-get-the-original-files-using-the-huggingface-datasets-platform

**Comment by MAHMOUDRR707** [comment]
@Uinelj  working fine with git lfs thankk you

**Comment by Uinelj** [comment]
@MAHMOUDRR707 the script is now here so you can also use `load_dataset` 🎉
