### ISSUE TITLE
harmful pp

### ISSUE THREAD

**Issue by jiangix-paper** [oscar-project/corpus#23]
Hello. Thanks for great job. I want to know the meaning of 'harmful pp', and is it smaller the better？

**Comment by Uinelj** [comment]
Hello.

A small `harmful_pp` value indicates that a document is similar to documents that are tagged as `adult` on the blocklist we use, so if you plan on removing adult content, you should inspect (then filter out if applicable) documents with low `harmful_pp` value.

You can find more details here: https://arxiv.org/abs/2212.10440

Let me know if you need more info on that matter!
